Update Build.yml

diff --git a/.github/workflows/Build.yml b/.github/workflows/Build.yml
--- a/.github/workflows/Build.yml
+++ b/.github/workflows/Build.yml
@@ -54,9 +54,14 @@ jobs:
           sudo apt-get update
           sudo apt-get install -y build-essential libncurses-dev make4.1+ perl python3.7+ which grep libc-dev asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3 unzip zlib1g-dev lib32gcc-s1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler g++-multilib antlr3 gperf wget curl swig rsync
 
+      - name: Checkout
+        uses: actions/checkout@v3
+        with:
+          fetch-depth: 1
+
       - name: 克隆源代码
         run: |
-          git clone -b ${{ github.event.inputs.branch }} https://github.com/openwrt/openwrt openwrt
+          git clone --depth 1 -b ${{ github.event.inputs.branch }} https://github.com/openwrt/openwrt openwrt
           cd openwrt
           # 根据设备架构选择正确的配置文件路径
           if [ "${{ github.event.inputs.device }}" == "x86_64" ]; then
@@ -66,7 +71,7 @@ jobs:
             cp -r ../configs/r3g/.config .
             cp -r ../configs/r3g/feeds.conf.default .
           fi
-
+      
       - name: 运行diy-part1.sh
         run: |
           cd openwrt
@@ -96,7 +101,15 @@ jobs:
         id: compile
         run: |
           cd openwrt
-          make V=s -j2 || { echo 'Build failed'; exit 1; }
+          make V=s -j2 > build.log || { echo 'Build failed'; cat build.log; exit 1; }
+        continue-on-error: true
+
+      - name: 上传生成日志
+        if: failure()
+        uses: actions/upload-artifact@v2
+        with:
+          name: build-log
+          path: openwrt/build.log
 
       - name: 创建发布
         id: create_release
